// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab3_asp.NET.API.Contexts;

namespace lab3_asp.NET.API.Migrations
{
    [DbContext(typeof(PersonDbContext))]
    partial class PersonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("lab3_asp.NET.Models.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterestId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestId = 1,
                            Description = "Programming websites and smart contracts",
                            Title = "Programming"
                        },
                        new
                        {
                            InterestId = 2,
                            Description = "Play videogames with friends",
                            Title = "Gaming"
                        },
                        new
                        {
                            InterestId = 3,
                            Description = "Travel the world",
                            Title = "Travel"
                        });
                });

            modelBuilder.Entity("lab3_asp.NET.Models.Link", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LinkId");

                    b.HasIndex("InterestId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            LinkId = 1,
                            InterestId = 1,
                            Url = "https://rinkeby.etherscan.io/"
                        },
                        new
                        {
                            LinkId = 2,
                            InterestId = 1,
                            Url = "https://www.codecademy.com/learn/react-101"
                        },
                        new
                        {
                            LinkId = 3,
                            InterestId = 1,
                            Url = "https://stackoverflow.com/"
                        },
                        new
                        {
                            LinkId = 4,
                            InterestId = 3,
                            Url = "https://www.trivago.se/"
                        },
                        new
                        {
                            LinkId = 5,
                            InterestId = 2,
                            Url = "https://www.pcgamer.com/news/"
                        });
                });

            modelBuilder.Entity("lab3_asp.NET.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Name = "Peter",
                            TelephoneNumber = "070945094590"
                        },
                        new
                        {
                            PersonId = 2,
                            Name = "Håkan",
                            TelephoneNumber = "0090489283"
                        },
                        new
                        {
                            PersonId = 3,
                            Name = "Mendela",
                            TelephoneNumber = "090032940"
                        },
                        new
                        {
                            PersonId = 4,
                            Name = "Maja",
                            TelephoneNumber = "078578748834"
                        },
                        new
                        {
                            PersonId = 5,
                            Name = "Sandra",
                            TelephoneNumber = "0809504905940"
                        });
                });

            modelBuilder.Entity("lab3_asp.NET.Models.PersonInterest", b =>
                {
                    b.Property<int>("PersonInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("PersonInterestId");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonInterests");

                    b.HasData(
                        new
                        {
                            PersonInterestId = 1,
                            InterestId = 1,
                            PersonId = 1
                        },
                        new
                        {
                            PersonInterestId = 2,
                            InterestId = 2,
                            PersonId = 1
                        },
                        new
                        {
                            PersonInterestId = 3,
                            InterestId = 3,
                            PersonId = 2
                        },
                        new
                        {
                            PersonInterestId = 4,
                            InterestId = 2,
                            PersonId = 3
                        },
                        new
                        {
                            PersonInterestId = 5,
                            InterestId = 1,
                            PersonId = 4
                        },
                        new
                        {
                            PersonInterestId = 6,
                            InterestId = 2,
                            PersonId = 4
                        },
                        new
                        {
                            PersonInterestId = 7,
                            InterestId = 3,
                            PersonId = 4
                        },
                        new
                        {
                            PersonInterestId = 8,
                            InterestId = 2,
                            PersonId = 5
                        },
                        new
                        {
                            PersonInterestId = 9,
                            InterestId = 3,
                            PersonId = 1
                        });
                });

            modelBuilder.Entity("lab3_asp.NET.Models.Link", b =>
                {
                    b.HasOne("lab3_asp.NET.Models.Interest", "Interest")
                        .WithMany("Links")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lab3_asp.NET.Models.PersonInterest", b =>
                {
                    b.HasOne("lab3_asp.NET.Models.Interest", "Interest")
                        .WithMany("PersonInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lab3_asp.NET.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
